[117] Added keywords KeyUp, KeyDown MouseMove on region and location
MarketSquare/robotframework-SikuliLibrary pull request #118
Opened 2019-12-09 12:36 UTC by rajeshtaneja

2020-02-03 05:47 UTC, rajeshtaneja commented
@rainmanwy , can you please review and if feel good for the project merge it ? Thanks.

2020-02-04 07:16 UTC, rainmanwy commented
@rajeshtaneja , so you replace the old "mouse move" implementation. right?
could you name your "mouse move" to other keyword name?
Thank you very much!

2020-02-05 16:51 UTC, edsonharantes commented on src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java
> +            + "\n\n @cooridnates: cooridnates where mouse should move"
Should be coordinates not cooridnates right? There are other parts that are written like this.

2021-04-15 18:59 UTC, stinnett-casey requested changes
The Mouse move that was added that is Mouse Move Region needs its keyword changed to `Mouse move region` and then it should be good to go. Nice work.

2021-04-15 19:02 UTC, stinnett-casey commented on src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java
> +    @RobotKeyword("Mouse move"
@rajeshtaneja 
Make this `@RobotKeyword("Mouse move region"

2021-04-15 19:40 UTC, stinnett-casey commented
A `Mouse Move Offset` would be a nice addition as well. I don't think that would be too much to add to this.

2021-04-21 22:57 UTC, stinnett-casey commented
For anyone else looking for how to have these options until they get merged, here is a solution I found in the meantime:
I wrote a custom python file and imported both the `keyboard` and the `mouse` module. You can easily combine those to do these things.
You can hold a key pressed: `keyboard.press('alt')` , sleep for a bit so it doesn't go too fast (time.sleep(.2)), then click: `mouse.click()`, then release the key: `keyboard.release('alt')`.

You can also use `mouse.move` to move relative to the cursor's position or straight to some x,y coords. Here are the docs:
https://github.com/boppreh/mouse
https://github.com/boppreh/keyboard

2021-05-12 03:05 UTC, rajeshtaneja commented
Sorry guys, was not keeping any eye on this. Will update patch soon. Thanks.
@Vigneshbecse  how can I help ?

2021-06-17 19:21 UTC, stinnett-casey commented
I have copied the code over, fixed the spelling of "coordinates", and made the change to "mouse move region" instead of "mouse move" so there is no conflict. It is ready to be merged if approved: #154

2025-05-04 17:50 UTC, closed without merging